"""Test and check commands for CARTS CLI."""

from pathlib import Path
from typing import List, Optional, Tuple
import subprocess
import os
import sys

import typer

from carts_styles import Colors, console, print_error, print_info, print_success
from scripts.config import PlatformConfig, get_config
from scripts.run import run_subprocess


def _resolve_lit_tool_paths(config: PlatformConfig) -> Tuple[Path, Path, Path]:
    """Resolve required test tools from the install tree."""
    return (
        config.get_llvm_tool("llvm-lit"),
        config.get_llvm_tool("FileCheck"),
        config.get_carts_tool("carts-compile"),
    )


def _setup_lit_pythonpath(config: PlatformConfig) -> None:
    """Configure PYTHONPATH so `llvm-lit` can import `lit` reliably."""
    lit_python_paths: List[str] = []

    # 1) Standard install location for Python modules under LLVM prefix.
    try:
        result = subprocess.run(
            ["python3", "-c",
             "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"],
            capture_output=True,
            text=True,
        )
        python_version = result.stdout.strip()
        llvm_python_path = config.llvm_install_dir / "lib" / \
            f"python{python_version}" / "site-packages"
        if llvm_python_path.is_dir():
            lit_python_paths.append(str(llvm_python_path))
    except Exception:
        pass

    # 2) Runtime location expected by llvm-lit launcher generated by LLVM.
    llvm_lit_runtime = config.llvm_install_dir / "utils" / "lit"
    if (llvm_lit_runtime / "lit").is_dir():
        lit_python_paths.append(str(llvm_lit_runtime))

    # Backward-compatible location used by older bootstrap scripts.
    llvm_lit_runtime_legacy = config.llvm_install_dir / "llvm" / "utils" / "lit"
    if (llvm_lit_runtime_legacy / "lit").is_dir():
        lit_python_paths.append(str(llvm_lit_runtime_legacy))

    # 3) Source fallback if user has not bootstrapped install-side lit yet.
    source_lit_runtime = config.carts_dir / "external" / "Polygeist" / \
        "llvm-project" / "llvm" / "utils" / "lit"
    if (source_lit_runtime / "lit").is_dir():
        lit_python_paths.append(str(source_lit_runtime))

    if not lit_python_paths:
        return

    deduped_paths: List[str] = []
    for path in lit_python_paths:
        if path not in deduped_paths:
            deduped_paths.append(path)

    env_pythonpath = os.environ.get("PYTHONPATH", "")
    if env_pythonpath:
        deduped_paths.append(env_pythonpath)
    os.environ["PYTHONPATH"] = os.pathsep.join(deduped_paths)


def _run_lit_suite(suite: str, verbose_tests: bool) -> None:
    """Run a lit suite and terminate the command with its exit code."""
    config = get_config()
    print_info("Running CARTS test suite...")

    tests_dir = config.carts_dir / "tests"
    if not tests_dir.is_dir():
        print_error(f"Tests directory not found at {tests_dir}")
        raise typer.Exit(1)

    llvm_lit, filecheck, carts_compile = _resolve_lit_tool_paths(config)

    missing = []
    if not llvm_lit.is_file():
        missing.append(f"llvm-lit ({llvm_lit})")
    if not filecheck.is_file():
        missing.append(f"FileCheck ({filecheck})")
    if not carts_compile.is_file():
        missing.append(f"carts-compile ({carts_compile})")

    if missing:
        print_error("Required test tools not found:")
        for tool in missing:
            console.print(f"  - {tool}")
        print_info(
            "Run `carts build` to install llvm-lit/FileCheck/carts-compile under .install/."
        )
        raise typer.Exit(1)

    suite_aliases = {"arts": "examples"}
    effective_suite = suite_aliases.get(suite, suite)
    if suite == "arts":
        print_info("Suite 'arts' is deprecated; using 'examples'.")

    if effective_suite == "all":
        # Keep "all" deterministic and green by running maintained lit suites.
        test_paths = [tests_dir / "contracts"]
    elif effective_suite == "contracts":
        test_paths = [tests_dir / "contracts"]
    elif effective_suite == "examples":
        test_paths = [tests_dir / "examples"]
    else:
        print_error(f"Unknown test suite '{suite}'")
        print_info("Available suites: all, contracts, examples")
        raise typer.Exit(1)

    for test_path in test_paths:
        if not test_path.is_dir():
            print_error(f"Test path not found: {test_path}")
            raise typer.Exit(1)

    _setup_lit_pythonpath(config)

    console.print(
        f"Test suite: [{Colors.INFO}]{effective_suite}[/{Colors.INFO}]")
    for path in test_paths:
        console.print(f"Test path: [dim]{path}[/dim]")
    console.print()

    cmd = [str(llvm_lit)]
    if verbose_tests:
        cmd.append("-v")
    for path in test_paths:
        cmd.append(str(path))

    result = run_subprocess(cmd, check=False)
    console.print()
    if result.returncode == 0:
        print_success("CARTS test suite completed successfully!")
    else:
        print_error(f"CARTS test suite failed with exit code {result.returncode}")
    raise typer.Exit(result.returncode)


def _run_examples() -> None:
    """Run the full example compilation+execution test suite."""
    from scripts.examples import examples_app
    # Invoke the examples app with "run --all" arguments
    try:
        examples_app(["run", "--all"], standalone_mode=False)
    except SystemExit as e:
        raise typer.Exit(e.code if e.code else 0)


def test(
    suite: str = typer.Option("all", "--suite", "-s",
                              help="Test suite: all, contracts, examples"),
    verbose_tests: bool = typer.Option(
        False, "-v", help="Verbose test output"),
    examples: bool = typer.Option(
        False, "--examples",
        help="Run full example compilation+execution test suite"),
):
    """Run CARTS test suite using llvm-lit."""
    if examples:
        _run_examples()
    else:
        _run_lit_suite(suite=suite, verbose_tests=verbose_tests)


def check(
    suite: str = typer.Option("all", "--suite", "-s",
                              help="Test suite: all, contracts, examples"),
    verbose_tests: bool = typer.Option(
        False, "-v", help="Verbose test output"),
    examples: bool = typer.Option(
        False, "--examples",
        help="Run full example compilation+execution test suite"),
):
    """Alias for `carts test`."""
    if examples:
        _run_examples()
    else:
        _run_lit_suite(suite=suite, verbose_tests=verbose_tests)
