#!/usr/bin/env bash
# Auto-generated by dekk — blocks raw build tool usage.
# Exit 2 = block the tool call.  Exit 0 = allow.

if ! command -v jq >/dev/null 2>&1; then
    exit 0
fi

INPUT=$(cat)
CMD=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty')

if printf '%s' "$CMD" | grep -qwE 'cmake|ninja|make'; then
  echo "Use dekk instead of raw build tools (cmake, ninja, make)" >&2
  exit 2
fi

exit 0
