#!/usr/bin/env bash
# Auto-generated by dekk — blocks raw build tool usage.
# Exit 2 = block the tool call.  Exit 0 = allow.

INPUT=$(cat)
CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

if echo "$CMD" | grep -qwE 'cmake|ninja|make'; then
  echo "Use dekk instead of raw build tools (cmake, ninja, make)" >&2
  exit 2
fi

exit 0
