- - - - - - - - - - - - - - - - - - 
- EDT #1 - "edt_1.main"
  - Type: main
  - Data Environment:
    - Number of ParamV = 0
    - Number of DepV = 0
  - Incoming Edges:
    - The EDT has no incoming Creation edges
    - The EDT has no incoming DataBlock slots
  - Outgoing Edges:
    - [Creation] "EDT #0"
    - [Creation] "EDT #2"
    - [DataBlock] "EDT #0" in Slot #0
      -   %shared_number = alloca i32, align 4
    - [DataBlock] "EDT #0" in Slot #1
      -   %random_number = alloca i32, align 4

- - - - - - - - - - - - - - - - - - 
- EDT #0 - "edt_0.sync"
  - Type: sync
  - Data Environment:
    - Number of ParamV = 0
    - Number of DepV = 2
      - ptr %0
      - ptr %1
  - Incoming Edges:
    - [Creation] "EDT #1"
  - Incoming DataBlock Slots:
    - EDTSlot #0
      - [DataBlock]   %shared_number = alloca i32, align 4
    - EDTSlot #1
      - [DataBlock]   %random_number = alloca i32, align 4
  - Outgoing Edges:
    - [Creation] "EDT #4"
    - [Creation] "EDT #6"
    - [DataBlock] "EDT #4" in Slot #1
      - ptr %1
    - [DataBlock] "EDT #4" in Slot #0
      - ptr %0

- - - - - - - - - - - - - - - - - - 
- EDT #2 - "edt_2.task"
  - Type: task
  - Data Environment:
    - Number of ParamV = 0
    - Number of DepV = 2
      - ptr %shared_number
      - ptr %random_number
  - Incoming Edges:
    - [Creation] "EDT #1"
  - Incoming DataBlock Slots:
    - EDTSlot #0
      - [DataBlock] ptr %0 /   %random_number = alloca i32, align 4
    - EDTSlot #1
      - [DataBlock] ptr %0 /   %shared_number = alloca i32, align 4
  - Outgoing Edges:
    - The EDT has no outgoing creation edges

- - - - - - - - - - - - - - - - - - 
- EDT #4 - "edt_4.sync"
  - Type: sync
  - Data Environment:
    - Number of ParamV = 0
    - Number of DepV = 2
      - ptr %0
      - ptr %1
  - Incoming Edges:
    - [Creation] "EDT #0"
  - Incoming DataBlock Slots:
    - EDTSlot #0
      - [DataBlock] ptr %0
    - EDTSlot #1
      - [DataBlock] ptr %1
  - Outgoing Edges:
    - [Creation] "EDT #3"
    - [DataBlock] "EDT #3" in Slot #0
      - ptr %0 / ptr %0
    - [DataBlock] "EDT #6" in Slot #0
      - ptr %1

- - - - - - - - - - - - - - - - - - 
- EDT #6 - "edt_6.task"
  - Type: task
  - Data Environment:
    - Number of ParamV = 0
    - Number of DepV = 2
      - ptr %0
      - ptr %1
  - Incoming Edges:
    - [Creation] "EDT #0"
  - Incoming DataBlock Slots:
    - EDTSlot #0
      - [DataBlock] ptr %1
      - [DataBlock] ptr %0 / ptr %0
  - Outgoing Edges:
    - [Creation] "EDT #5"
    - [DataBlock] "EDT #5" in Slot #0
      - ptr %0 /   %random_number = alloca i32, align 4
    - [DataBlock] "EDT #2" in Slot #1
      - ptr %0 /   %shared_number = alloca i32, align 4

- - - - - - - - - - - - - - - - - - 
- EDT #3 - "edt_3.task"
  - Type: task
  - Data Environment:
    - Number of ParamV = 1
      - i32 %1
    - Number of DepV = 1
      - ptr %0
  - Incoming Edges:
    - [Creation] "EDT #4"
  - Incoming DataBlock Slots:
    - EDTSlot #0
      - [DataBlock] ptr %0 / ptr %0
  - Outgoing Edges:
    - The EDT has no outgoing creation edges
    - [DataBlock] "EDT #6" in Slot #0
      - ptr %0 / ptr %0

- - - - - - - - - - - - - - - - - - 
- EDT #5 - "edt_5.task"
  - Type: task
  - Data Environment:
    - Number of ParamV = 1
      - i32 %1
    - Number of DepV = 1
      - ptr %0
  - Incoming Edges:
    - [Creation] "EDT #6"
  - Incoming DataBlock Slots:
    - EDTSlot #0
      - [DataBlock] ptr %0 /   %random_number = alloca i32, align 4
  - Outgoing Edges:
    - The EDT has no outgoing creation edges
    - [DataBlock] "EDT #2" in Slot #0
      - ptr %0 /   %random_number = alloca i32, align 4