#!/usr/bin/env python3
"""MCP server for carts — auto-generated by dekk.

Wraps project commands as MCP tools for AI coding assistants.
Regenerate with: dekk carts skills generate
"""

from __future__ import annotations

import asyncio
import json
import shlex

from mcp.server.fastmcp import FastMCP

server = FastMCP("carts")

@server.tool()
async def carts_build(args: str = "") -> str:
    """Build CARTS and related components"""
    cmd = shlex.split("dekk carts build") + shlex.split(args)
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return json.dumps({
        "exit_code": proc.returncode,
        "stdout": stdout.decode(errors="replace"),
        "stderr": stderr.decode(errors="replace"),
    })

@server.tool()
async def carts_compile(args: str = "") -> str:
    """Run the CARTS compilation pipeline"""
    cmd = shlex.split("dekk carts compile") + shlex.split(args)
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return json.dumps({
        "exit_code": proc.returncode,
        "stdout": stdout.decode(errors="replace"),
        "stderr": stderr.decode(errors="replace"),
    })

@server.tool()
async def carts_pipeline(args: str = "") -> str:
    """Inspect compiler pipeline stages"""
    cmd = shlex.split("dekk carts pipeline") + shlex.split(args)
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return json.dumps({
        "exit_code": proc.returncode,
        "stdout": stdout.decode(errors="replace"),
        "stderr": stderr.decode(errors="replace"),
    })

@server.tool()
async def carts_triage_benchmark(args: str = "") -> str:
    """Run the benchmark triage workflow"""
    cmd = shlex.split("dekk carts triage-benchmark") + shlex.split(args)
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return json.dumps({
        "exit_code": proc.returncode,
        "stdout": stdout.decode(errors="replace"),
        "stderr": stderr.decode(errors="replace"),
    })

@server.tool()
async def carts_test(args: str = "") -> str:
    """Run the CARTS test suite"""
    cmd = shlex.split("dekk carts test") + shlex.split(args)
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return json.dumps({
        "exit_code": proc.returncode,
        "stdout": stdout.decode(errors="replace"),
        "stderr": stderr.decode(errors="replace"),
    })

@server.tool()
async def carts_benchmarks(args: str = "") -> str:
    """Build and run benchmark workloads"""
    cmd = shlex.split("dekk carts benchmarks") + shlex.split(args)
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return json.dumps({
        "exit_code": proc.returncode,
        "stdout": stdout.decode(errors="replace"),
        "stderr": stderr.decode(errors="replace"),
    })

if __name__ == "__main__":
    server.run()
