#!/usr/bin/env python3
"""Generate arts.cfg configuration files with real cluster hostnames.

This script generates multiple arts.cfg files for multi-node execution,
each with incrementing node counts using actual cluster hostnames.

Usage:
    python3 tools/generate-arts-configs.py --prefix=e5-cse-135- --num=[01-24,27-28]
    python3 tools/generate-arts-configs.py --prefix=node --num=[1-10] --threads=32

Example:
    --prefix=e5-cse-135- --num=[01-24,27-28]

    Generates 26 config files:
    - arts_20t_01n.cfg: 1 node  (e5-cse-135-01)
    - arts_20t_02n.cfg: 2 nodes (e5-cse-135-01, e5-cse-135-02)
    - ...
    - arts_20t_26n.cfg: 26 nodes (all nodes)
"""

import argparse
import sys
from pathlib import Path
from typing import List


def parse_num_range(num_str: str) -> List[str]:
    """Parse a number range string into a list of formatted numbers.

    Examples:
        "[01-24,27-28]" -> ['01', '02', ..., '24', '27', '28']
        "[1-5]" -> ['1', '2', '3', '4', '5']
        "[01-03,05,07-09]" -> ['01', '02', '03', '05', '07', '08', '09']
    """
    # Remove brackets and whitespace
    num_str = num_str.strip('[]() ').strip()

    if not num_str:
        raise ValueError("Empty number range")

    result = []
    for part in num_str.split(','):
        part = part.strip()
        if '-' in part:
            # Range: "01-24" or "1-5"
            start_str, end_str = part.split('-', 1)
            start_str = start_str.strip()
            end_str = end_str.strip()

            # Determine width for zero-padding
            width = len(start_str)

            start = int(start_str)
            end = int(end_str)

            if start > end:
                raise ValueError(f"Invalid range: {part} (start > end)")

            for i in range(start, end + 1):
                result.append(str(i).zfill(width))
        else:
            # Single number: "05" or "5"
            result.append(part)

    return result


def generate_hostnames(prefix: str, numbers: List[str]) -> List[str]:
    """Generate hostnames by combining prefix with numbers."""
    return [f"{prefix}{num}" for num in numbers]


def generate_arts_cfg(
    hostnames: List[str],
    node_count: int,
    threads: int,
    port: int,
) -> str:
    """Generate arts.cfg content for a specific number of nodes."""
    # Use first node_count hostnames
    active_hosts = hostnames[:node_count]
    nodes_list = ",".join([f"{host}:{port}" for host in active_hosts])
    master_node = active_hosts[0]

    config = f"""[ARTS]
# Generated by generate-arts-configs.py
# Configuration: {threads} threads, {node_count} node(s)

# Threading
threads={threads}
tMT=0

# Node configuration
nodeCount={node_count}
nodes={nodes_list}
masterNode={master_node}

# Launcher
launcher=ssh
port={port}

# Scheduling
workerInitDequeSize=2048
routeTableSize=16

# Hardware
pin=1
pinStride=1

# Network
outgoing=1
incoming=1
ports=1
protocol=tcp
"""
    return config


def main():
    parser = argparse.ArgumentParser(
        description="Generate arts.cfg files with real cluster hostnames.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --prefix=e5-cse-135- --num=[01-24,27-28]
  %(prog)s --prefix=node --num=[1-10] --threads=32 --output=./my-configs
        """
    )
    parser.add_argument(
        "--prefix",
        required=True,
        help="Hostname prefix (e.g., 'e5-cse-135-', 'node')"
    )
    parser.add_argument(
        "--num",
        required=True,
        help="Node number range (e.g., '[01-24,27-28]', '[1-10]')"
    )
    parser.add_argument(
        "--threads", "-t",
        type=int,
        default=20,
        help="Number of threads per node (default: 20)"
    )
    parser.add_argument(
        "--port", "-p",
        type=int,
        default=34739,
        help="ARTS port (default: 34739)"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=Path("./configs"),
        help="Output directory (default: ./configs)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be generated without creating files"
    )

    args = parser.parse_args()

    # Parse number range
    try:
        numbers = parse_num_range(args.num)
    except ValueError as e:
        print(f"ERROR: Failed to parse --num: {e}")
        sys.exit(1)

    if not numbers:
        print("ERROR: No nodes specified")
        sys.exit(1)

    # Generate hostnames
    hostnames = generate_hostnames(args.prefix, numbers)
    total_nodes = len(hostnames)

    print(f"Prefix: {args.prefix}")
    print(f"Numbers: {args.num}")
    print(f"Total nodes: {total_nodes}")
    print(f"Threads per node: {args.threads}")
    print(f"Port: {args.port}")
    print(f"Output: {args.output}")
    print()
    print("Hostnames:")
    for i, host in enumerate(hostnames, 1):
        print(f"  {i:2d}. {host}")
    print()

    if args.dry_run:
        print("[Dry run - not creating files]")
        return

    # Create output directory
    args.output.mkdir(parents=True, exist_ok=True)

    # Generate config files
    print(f"Generating {total_nodes} configuration files...")
    for node_count in range(1, total_nodes + 1):
        config_content = generate_arts_cfg(
            hostnames,
            node_count,
            args.threads,
            args.port,
        )

        # Filename: arts_20t_01n.cfg, arts_20t_02n.cfg, etc.
        filename = f"arts_{args.threads}t_{node_count:02d}n.cfg"
        filepath = args.output / filename
        filepath.write_text(config_content)
        print(f"  Created: {filepath}")

    print()
    print(f"Generated {total_nodes} config files in {args.output}")


if __name__ == "__main__":
    main()
