#!/usr/bin/env python3
"""Generate LLVM IR (.ll) files for all CARTS benchmarks with varying node counts.

This script compiles all benchmarks in carts-benchmarks to LLVM IR format,
generating separate .ll files for different node configurations. This is useful
for cross-compilation scenarios where the CARTS compiler runs on one system
and the final linking happens on another.

Uses the existing Makefile build system which produces -arts.ll files as a byproduct.

Usage:
    python3 tools/generate-ll-files.py --output ./ll-output
    python3 tools/generate-ll-files.py --output ./ll-output --benchmark polybench/gemm
    python3 tools/generate-ll-files.py --output ./ll-output --threads 20 --max-nodes 28
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple


@dataclass
class BenchmarkInfo:
    """Information about a single benchmark."""
    name: str
    path: Path
    suite: str


def find_carts_benchmarks_root() -> Path:
    """Find the carts-benchmarks directory."""
    script_dir = Path(__file__).resolve().parent
    carts_root = script_dir.parent
    benchmarks_root = carts_root / "external" / "carts-benchmarks"
    if not benchmarks_root.exists():
        raise RuntimeError(f"Cannot find carts-benchmarks at {benchmarks_root}")
    return benchmarks_root


def is_benchmark_disabled(bench_dir: Path) -> Tuple[bool, str]:
    """Check if a benchmark is disabled and return reason."""
    if (bench_dir / ".disable-multinode").exists():
        return True, "has .disable-multinode marker"
    if (bench_dir / ".disabled").exists():
        return True, "has .disabled marker"
    return False, ""


def get_suite_name(bench_path: Path, benchmarks_root: Path) -> str:
    """Get the suite name for a benchmark path."""
    relative = bench_path.relative_to(benchmarks_root)
    parts = relative.parts
    if len(parts) >= 2:
        return parts[0]
    elif len(parts) == 1:
        return parts[0]
    return "misc"


def discover_benchmarks(
    benchmarks_root: Path,
    filter_benchmark: Optional[str] = None
) -> List[BenchmarkInfo]:
    """Discover all enabled benchmarks in carts-benchmarks."""
    benchmarks = []

    for makefile_path in benchmarks_root.rglob("Makefile"):
        bench_dir = makefile_path.parent

        # Skip common directories
        if "common" in bench_dir.parts or "utilities" in bench_dir.parts:
            continue

        # Skip if Makefile doesn't have EXAMPLE_NAME (not a benchmark)
        content = makefile_path.read_text()
        match = re.search(r'^EXAMPLE_NAME\s*:?=\s*(\S+)', content, re.MULTILINE)
        if not match:
            continue

        name = match.group(1)

        # Check if disabled
        disabled, reason = is_benchmark_disabled(bench_dir)
        if disabled:
            print(f"  Skipping {bench_dir.name}: {reason}")
            continue

        # Get suite name
        suite = get_suite_name(bench_dir, benchmarks_root)

        # Filter if requested
        if filter_benchmark:
            filter_path = f"{suite}/{bench_dir.name}"
            if filter_benchmark not in filter_path:
                continue

        benchmarks.append(BenchmarkInfo(
            name=name,
            path=bench_dir,
            suite=suite,
        ))

    return sorted(benchmarks, key=lambda b: (b.suite, b.name))


def generate_arts_cfg(output_path: Path, threads: int, node_count: int) -> None:
    """Generate an arts.cfg file with placeholder node names."""
    nodes_list = ",".join([f"node{i}:34739" for i in range(1, node_count + 1)])

    config = f"""[ARTS]
# Generated by generate-ll-files.py
# Configuration: {threads} threads, {node_count} nodes

# Threading
threads={threads}
tMT=0

# Node configuration
nodeCount={node_count}
nodes={nodes_list}
masterNode=node1

# Launcher
launcher=ssh
port=34739

# Scheduling
workerInitDequeSize=2048
routeTableSize=16

# Hardware
pin=1
pinStride=1

# Network
outgoing=1
incoming=1
ports=1
protocol=tcp
"""
    output_path.write_text(config)


def run_make(bench_dir: Path, target: str, arts_cfg: Optional[Path] = None,
             capture_output: bool = True) -> subprocess.CompletedProcess:
    """Run make in a benchmark directory."""
    cmd = ["make", target]
    if arts_cfg:
        cmd.append(f"ARTS_CFG={arts_cfg}")

    try:
        result = subprocess.run(
            cmd,
            cwd=bench_dir,
            capture_output=capture_output,
            text=True,
            timeout=600  # 10 minute timeout
        )
        return result
    except subprocess.TimeoutExpired:
        print(f"  ERROR: Make timed out for {bench_dir.name}")
        raise


def process_benchmark(
    benchmark: BenchmarkInfo,
    output_base: Path,
    threads: int,
    max_nodes: int,
    cfg_dir: Path,
    size: str,
) -> Tuple[int, int]:
    """Process a single benchmark, generating .ll files for all node counts.

    Returns:
        Tuple of (success_count, failure_count)
    """
    print(f"\n[{benchmark.suite}/{benchmark.name}]")

    # Create output directory
    output_dir = output_base / benchmark.suite / benchmark.name
    output_dir.mkdir(parents=True, exist_ok=True)

    # The generated .ll file name from make
    ll_filename = f"{benchmark.name}-arts.ll"
    ll_src = benchmark.path / ll_filename

    success = 0
    failure = 0

    # Make target based on size
    make_target = f"{size.lower()}-arts"

    for nodes in range(1, max_nodes + 1):
        # Generate arts.cfg for this node count
        cfg_file = cfg_dir / f"arts_{threads}t_{nodes}n.cfg"
        if not cfg_file.exists():
            generate_arts_cfg(cfg_file, threads, nodes)

        # Clean previous build artifacts
        run_make(benchmark.path, "clean", capture_output=True)

        # Build with the specific arts.cfg
        result = run_make(benchmark.path, make_target, arts_cfg=cfg_file)

        if result.returncode != 0:
            print(f"  FAILED: nodes={nodes}")
            if result.stderr:
                # Show last few lines of error
                lines = result.stderr.strip().split('\n')
                for line in lines[-5:]:
                    print(f"    {line}")
            failure += 1
            continue

        # Check if .ll file was generated
        if not ll_src.exists():
            print(f"  FAILED: nodes={nodes} (no .ll file generated)")
            failure += 1
            continue

        # Copy to output directory with node count suffix
        ll_dest = output_dir / f"{benchmark.name}_n{nodes:02d}.ll"
        shutil.copy2(ll_src, ll_dest)
        success += 1

    print(f"  Generated {success}/{max_nodes} .ll files")
    return success, failure


def main():
    parser = argparse.ArgumentParser(
        description="Generate LLVM IR files for CARTS benchmarks with varying node counts."
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=Path("./ll-output"),
        help="Output directory for .ll files (default: ./ll-output)"
    )
    parser.add_argument(
        "--threads", "-t",
        type=int,
        default=20,
        help="Number of threads per node (default: 20)"
    )
    parser.add_argument(
        "--max-nodes", "-n",
        type=int,
        default=28,
        help="Maximum number of nodes (default: 28)"
    )
    parser.add_argument(
        "--size", "-s",
        choices=["SMALL", "MEDIUM", "LARGE", "EXTRALARGE"],
        default="EXTRALARGE",
        help="Benchmark size variant (default: EXTRALARGE)"
    )
    parser.add_argument(
        "--benchmark", "-b",
        type=str,
        default=None,
        help="Filter to specific benchmark (e.g., 'polybench/gemm')"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="List benchmarks without compiling"
    )

    args = parser.parse_args()

    # Find benchmarks root
    try:
        benchmarks_root = find_carts_benchmarks_root()
    except RuntimeError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    print(f"CARTS Benchmarks: {benchmarks_root}")
    print(f"Output directory: {args.output}")
    print(f"Configuration: {args.threads} threads, 1-{args.max_nodes} nodes, {args.size} size")
    print()

    # Discover benchmarks
    print("Discovering benchmarks...")
    benchmarks = discover_benchmarks(
        benchmarks_root,
        filter_benchmark=args.benchmark
    )

    print(f"\nFound {len(benchmarks)} enabled benchmarks:")
    for b in benchmarks:
        print(f"  {b.suite}/{b.name}")

    if args.dry_run:
        print("\n[Dry run - not compiling]")
        return

    # Create output directory
    args.output.mkdir(parents=True, exist_ok=True)

    # Create config directory (persistent, not in temp)
    cfg_dir = args.output / ".configs"
    cfg_dir.mkdir(exist_ok=True)

    # Process each benchmark
    total_success = 0
    total_failure = 0

    for benchmark in benchmarks:
        success, failure = process_benchmark(
            benchmark,
            args.output,
            args.threads,
            args.max_nodes,
            cfg_dir,
            args.size,
        )
        total_success += success
        total_failure += failure

    # Summary
    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    expected = len(benchmarks) * args.max_nodes
    print(f"Benchmarks processed: {len(benchmarks)}")
    print(f"Node configurations: 1-{args.max_nodes}")
    print(f"Expected .ll files: {expected}")
    print(f"Generated: {total_success}")
    print(f"Failed: {total_failure}")
    print(f"\nOutput: {args.output}")

    # Count actual files
    actual_files = list(args.output.rglob("*.ll"))
    print(f"Actual .ll files: {len(actual_files)}")

    if total_failure > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
